name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install deps
        run: npm ci
      - name: Lint
        uses: Bidaya0/sql-lint-in-action@v0.0.3
